name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=18"
      - name: npm test
        run: |
          npm install
          npm test
  automerge:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: [test]
    permissions: write-all
    steps:
      - name: Apply automerge label
        run: gh pr edit "$PR_URL" --add-label "automerge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Automerge
        run: gh pr merge -m "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.5
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Authenticate to Artifact Registry
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev
      - name: Build Docker image and push to GAR
        env:
          IMAGE_TAG: v1.0.${{ github.run_number }}
          AR_REPO: europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/maven-badges/maven-badges
        run: |
          docker build -t $AR_REPO:$IMAGE_TAG -t $AR_REPO:latest .
          docker push $AR_REPO:$IMAGE_TAG
          docker push $AR_REPO:latest
